version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment: 
      - "discovery.type=sigle-node"
    volumes:
      - .\elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elashticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elknetwork
  kibana:
    image: kibana:7.7.0
    container_name: kibana
    hostname: kibana
    volumes:
      - .\kibana\kibana.yml:/usr/share/kibana/kibana.yml
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
  logstash:
    image: logstash:7.7.0
    container_name: logstash
    hostname: logstash
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    volumes:
      - .\logstash\pipeline:/usr/share/logstash/pipeline/
      - .\logstash\logstash.yml:/usr/share/logstash/logstash.yml
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elknetwork
networks:
  elknetwork:
    driver: bridge